//! The deterministic `.d.ts` renderer.
//!
//! Turns a [`ModuleDef`] into a complete TypeScript declaration file.
//! The renderer is pure: the output depends only on the IR, so
//! re-rendering the same module always yields byte-identical output
//! (see the "Render guarantees" section of the crate docs).

use crate::ident::sanitize;
use crate::ir::{FunctionDef, ModuleDef};

/// Renders `module` as a complete TypeScript declaration file.
///
/// # Format contract
///
/// The exact output format is:
///
/// 1. Line 1: `// @generated by bffi-dts - do not edit.`
/// 2. Line 2: `// Source module: {module.name}`
/// 3. For each function, in declaration order: one empty line, then
///    the function block consisting of
///    - a JSDoc comment, rendered only when [`FunctionDef::docs`] is
///      non-empty: a single doc line renders as `/** {line} */`; two
///      or more render as a `/**` opening line, one ` * {line}` line
///      per doc line, and a ` */` closing line;
///    - `export function {js_name}({params}): {ret};` where `js_name`
///      and every parameter name are passed through [`sanitize`],
///      parameters are joined by `, ` as `name: type`, and every type
///      name comes from [`TsType::as_str`] (so [`TsType::Void`] renders
///      `void` with no special casing).
///
/// The output uses LF line endings throughout and ends with exactly
/// one trailing newline; a module with no functions therefore ends
/// right after its two header lines. No timestamps or version numbers
/// are embedded. [`FunctionDef::export_name`] is never rendered: it
/// exists for the build side only.
///
/// # Panics
///
/// Never panics: all slices are iterated, never indexed, names are
/// sanitized through the total (infallible) [`sanitize`], and the file
/// is built with `push_str`/`push` alone.
#[must_use]
pub fn render(module: &ModuleDef) -> String {
    let mut out = String::new();
    out.push_str("// @generated by bffi-dts - do not edit.\n");
    out.push_str("// Source module: ");
    out.push_str(module.name);
    out.push('\n');
    for function in module.fns {
        out.push('\n');
        push_function(function, &mut out);
    }
    out
}

/// Appends one function block: JSDoc (when docs are present) followed
/// by the `export function` declaration.
fn push_function(function: &FunctionDef, out: &mut String) {
    push_docs(function.docs, out);
    out.push_str("export function ");
    out.push_str(&sanitize(function.js_name));
    out.push('(');
    let mut first = true;
    for param in function.params {
        if !first {
            out.push_str(", ");
        }
        first = false;
        out.push_str(&sanitize(param.name));
        out.push_str(": ");
        out.push_str(param.ty.as_str());
    }
    out.push_str("): ");
    out.push_str(function.ret.as_str());
    out.push_str(";\n");
}

/// Appends the JSDoc block for `docs`, or nothing when `docs` is
/// empty: one line renders inline, two or more render as a block.
fn push_docs(docs: &[&str], out: &mut String) {
    if let [only] = docs {
        out.push_str("/** ");
        out.push_str(only);
        out.push_str(" */\n");
        return;
    }
    if docs.is_empty() {
        return;
    }
    out.push_str("/**\n");
    for line in docs {
        out.push_str(" * ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(" */\n");
}
