//! The declarative generator of the JS-facing async exports.
//!
//! [`bffi_async_abi!`] expands - in the USER crate, not here - into
//! the two exports JavaScript needs to drive tasks: `bffi_async_attach`
//! and `bffi_async_cancel`. Expansion must happen in the user crate
//! (the linker may drop unused `#[no_mangle]` symbols from rlib
//! dependencies); this mirrors the `bffi_runtime_abi!` model of
//! bffi-build.
//!
//! Justified deviation from "runtime ABI lives in bffi-build"
//! (HANDOFF 3.6): bffi-build cannot depend on bffi-async (async sits
//! above build for the transient-buffer deliveries - a dependency
//! would cycle), so the generator lives with its runtime.

/// Maps an [`crate::AttachError`]-shaped failure to the exported
/// [`bffi_core::ErrorCode`] numeric value with the last error stored.
pub(crate) fn store_attach_error(error: crate::AsyncError) -> u32 {
    let converted: bffi_core::BffiError = error.into();
    let code = converted.code;
    bffi_core::set_last_error(converted);
    code.as_u32()
}

/// Attaches a resolver pair and returns the exported
/// [`bffi_core::ErrorCode`] numeric value.
#[must_use]
pub fn attach_as_code(task: u64, resolve: usize, reject: usize) -> u32 {
    match crate::attach(bffi_core::Handle::from_raw(task), resolve, reject) {
        Ok(()) => bffi_core::ErrorCode::Ok.as_u32(),
        Err(error) => store_attach_error(error),
    }
}

/// Cancels the task and returns the exported
/// [`bffi_core::ErrorCode`] numeric value (`0` = a running task was
/// cancelled, `4` = invalid/stale handle or already finished).
#[must_use]
pub fn cancel_as_code(task: u64) -> u32 {
    if crate::cancel(bffi_core::Handle::from_raw(task)) {
        bffi_core::ErrorCode::Ok.as_u32()
    } else {
        bffi_core::ErrorCode::InvalidHandle.as_u32()
    }
}

/// Generates the two JS-facing async exports.
///
/// Call once, at the root of the cdylib crate (next to
/// `bffi_build::bffi_runtime_abi!()`). The user crate must depend on
/// `bffi-core` and `bffi-async`.
///
/// | Symbol | Signature | Returns |
/// | --- | --- | --- |
/// | `bffi_async_attach` | `(task: u64, resolve: u64, reject: u64, __ret: *mut u32) -> u32` | the `ErrorCode` numeric value; `13`-style errors carry the last error |
/// | `bffi_async_cancel` | `(task: u64) -> u32` | `0` = cancelled, `4` = invalid/stale or already finished |
#[macro_export]
macro_rules! bffi_async_abi {
    () => {
        /// C ABI export generated by `bffi_async_abi!()`: attaches the
        /// resolve/reject trampoline pair to a task.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_async_attach(
            task: u64,
            resolve: u64,
            reject: u64,
            __ret: *mut u32,
        ) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::abi::attach_as_code(task, resolve as usize, reject as usize)
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::abi::attach_as_code(task, resolve as usize, reject as usize),
                    ::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }

        /// C ABI export generated by `bffi_async_abi!()`: requests
        /// cancellation of a task.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_async_cancel(task: u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::abi::cancel_as_code(task)
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::abi::cancel_as_code(task),
                    ::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }
    };
}
