//! `extern "C"` shim codegen for classes (DESIGN §6.2, §6.5).
//!
//! Mirrors the `bffi-macros` build policy: debug builds run the body
//! bare (a panic aborts), release builds wrap it in
//! `::bffi_core::boundary::run_extern_body`. Every shim validates the
//! incoming handle through the `ObjectWrap`/Registry barriers (tag +
//! generation + null) before any use.
//!
//! Generated code never `expect`s or `panic!`s: a tag collision is
//! stored as the sticky `ObjectWrap` init outcome and surfaces as a
//! runtime error code - user crates compile under the same
//! `-D warnings` lints as the framework.

use crate::mapping::{BigIntTy, BufferTy, PrimTy, RetKind, ShimKind};
use crate::model::{ClassModel, ConstructorModel, FieldTy, ImplModel, MethodModel, MethodParam};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// The generated wrap-accessor identifier for a class.
pub(crate) fn wrap_ident(js_name: &str) -> proc_macro2::Ident {
    format_ident!("__bffi_{js_name}_wrap")
}

/// The match arm for an `Err(ObjectError)`: store, convert, return
/// the code. Inlined at every site so neither expansion depends on
/// the other's generated items; diverges with `return`, so it fits
/// both value positions and nested matches.
fn error_arm() -> TokenStream {
    quote! {
        {
            let converted: ::bffi_core::BffiError = error.into();
            let code = converted.code;
            ::bffi_core::set_last_error(converted);
            return code;
        }
    }
}

/// Renders the `#[bffi_class]` expansion tail: the wrap accessor plus
/// the release and field-getter shims.
pub(crate) fn class_shims(model: &ClassModel) -> TokenStream {
    let wrap_fn = wrap_ident(&model.js_name);
    let struct_ident = &model.ident;
    // Interpolated as a plain hex literal; the u16 conversion happens
    // at the call site (`TypeTag(<lit>)`).
    let tag_lit = syn::LitInt::new(
        &format!("{:#06x}", model.tag),
        proc_macro2::Span::call_site(),
    );
    let release_ident = format_ident!("bffi_{}_release", model.js_name);
    let release_doc = format!(
        "Releases the `{}` instance handle (generated by `#[bffi_class]`).",
        model.js_name
    );
    let getters = model.fields.iter().map(|field| field_getter(model, field));
    let release = shim_pair(
        &release_ident,
        &release_doc,
        quote! { handle: u64 },
        release_body(&wrap_fn),
    );

    quote! {
        /// Wrap accessor generated by `#[bffi_class]`: the
        /// process-wide [`::bffi_object::ObjectWrap`] for this type,
        /// claimed once. A tag collision stays sticky in the init
        /// result and surfaces as an error code on every call.
        fn #wrap_fn()
            -> ::std::result::Result<&'static ::bffi_object::ObjectWrap<#struct_ident>, ::bffi_object::ObjectError>
        {
            static WRAP: ::std::sync::OnceLock<
                ::std::result::Result<::bffi_object::ObjectWrap<#struct_ident>, ::bffi_object::ObjectError>,
            > = ::std::sync::OnceLock::new();
            match WRAP.get_or_init(|| ::bffi_object::ObjectWrap::new(::bffi_core::TypeTag(#tag_lit))) {
                ::std::result::Result::Ok(wrap) => ::std::result::Result::Ok(wrap),
                ::std::result::Result::Err(error) => ::std::result::Result::Err(*error),
            }
        }

        #(#getters)*

        #release
    }
}

/// The release transport body shared by both cfg variants.
fn release_body(wrap_fn: &proc_macro2::Ident) -> TokenStream {
    let error_arm = error_arm();
    quote! {
        match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.release(::bffi_core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(_arc) => ::bffi_core::ErrorCode::Ok,
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        }
    }
}

/// Renders one field-getter shim pair.
fn field_getter(model: &ClassModel, field: &crate::model::FieldModel) -> TokenStream {
    let getter_ident = format_ident!("bffi_{}_{}_get", model.js_name, field.name);
    let field_ident = format_ident!("{}", field.name);
    let getter_doc = format!(
        "Reads the `{}` field of a `{}` instance (generated by `#[bffi_class]`).",
        field.name, model.js_name
    );
    let out_ty = match field.ty {
        FieldTy::Prim(prim) => prim_ty(prim),
        FieldTy::BigInt(big) => bigint_ty(big),
    };
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm();
    let body = quote! {
        if __ret.is_null() {
            let error = ::bffi_core::BffiError::new(
                ::bffi_core::ErrorCode::NullPointer,
                "output pointer is null",
            );
            ::bffi_core::set_last_error(error);
            return ::bffi_core::ErrorCode::NullPointer;
        }
        let __arc = match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.get(::bffi_core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(arc) => arc,
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        };
        // SAFETY: `__ret` is non-null (checked above) and valid for one
        // write per the bun:ffi out-parameter contract.
        unsafe { ::std::ptr::write(__ret, __arc.#field_ident); }
        ::bffi_core::ErrorCode::Ok
    };
    shim_pair(
        &getter_ident,
        &getter_doc,
        quote! { handle: u64, __ret: *mut #out_ty },
        body,
    )
}

/// Renders the `#[bffi_impl]` expansion tail: the constructor and
/// method shims.
pub(crate) fn impl_shims(model: &ImplModel) -> TokenStream {
    let ctor = constructor_shim(model);
    let methods = model
        .methods
        .iter()
        .map(|method| method_shim(model, method));

    quote! {
        #ctor

        #(#methods)*
    }
}

/// Renders the constructor shim: runs the Rust constructor, wraps the
/// value, writes the handle.
fn constructor_shim(model: &ImplModel) -> TokenStream {
    let ctor: &ConstructorModel = &model.constructor;
    let shim_ident = format_ident!("bffi_{}_new", model.js_name);
    let shim_doc = format!(
        "Creates a `{}` instance and returns its handle (generated by `#[bffi_impl]`).",
        model.js_name
    );
    let type_ident = &model.type_ident;
    let ctor_ident = &ctor.ident;
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm();
    let params: Vec<TokenStream> = ctor
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| shim_param(param, index))
        .collect();
    let args = ctor.params.iter().enumerate().map(|(index, param)| {
        let name = param_ident(&param.name, index);
        match param.kind {
            ShimKind::Str => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            ShimKind::Prim(_) | ShimKind::BigInt(_) => quote! { #name },
        }
    });
    let conversion = str_conversions(&ctor.params);
    let body = quote! {
        if __ret.is_null() {
            let error = ::bffi_core::BffiError::new(
                ::bffi_core::ErrorCode::NullPointer,
                "output pointer is null",
            );
            ::bffi_core::set_last_error(error);
            return ::bffi_core::ErrorCode::NullPointer;
        }
        #conversion
        let __value = #type_ident::#ctor_ident(#(#args,)*);
        match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.wrap(__value) {
                    ::std::result::Result::Ok(handle) => {
                        // SAFETY: `__ret` is non-null (checked above) and valid
                        // for one `u64` write per the bun:ffi out-parameter contract.
                        unsafe { ::std::ptr::write(__ret, handle.as_u64()); }
                        ::bffi_core::ErrorCode::Ok
                    }
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        }
    };
    shim_pair(
        &shim_ident,
        &shim_doc,
        quote! { #(#params,)* __ret: *mut u64 },
        body,
    )
}

/// Renders one `&self` method shim pair.
fn method_shim(model: &ImplModel, method: &MethodModel) -> TokenStream {
    let shim_ident = format_ident!("bffi_{}_{}", model.js_name, method.ident);
    let shim_doc = format!(
        "Calls `{}::{}` on the instance behind the handle (generated by `#[bffi_impl]`).",
        model.type_ident, method.ident
    );
    let type_ident = &model.type_ident;
    let method_ident = &method.ident;
    let wrap_fn = wrap_ident(&model.js_name);
    let error_arm = error_arm();
    let params: Vec<TokenStream> = method
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| shim_param(param, index))
        .collect();
    let out = out_param(&method.ret);
    let args = method.params.iter().enumerate().map(|(index, param)| {
        let name = param_ident(&param.name, index);
        match param.kind {
            ShimKind::Str => {
                let view = format_ident!("{name}_view");
                quote! { &#view }
            }
            ShimKind::Prim(_) | ShimKind::BigInt(_) => quote! { #name },
        }
    });
    let conversion = str_conversions(&method.params);
    let call = quote! { #type_ident::#method_ident(&__arc, #(#args,)*) };
    let transport = ret_body(&method.ret, call);
    let body = quote! {
        #conversion
        let __arc = match #wrap_fn() {
            ::std::result::Result::Ok(wrap) => {
                match wrap.get(::bffi_core::Handle::from_raw(handle)) {
                    ::std::result::Result::Ok(arc) => arc,
                    ::std::result::Result::Err(error) => #error_arm,
                }
            }
            ::std::result::Result::Err(error) => #error_arm,
        };
        #transport
    };
    shim_pair(
        &shim_ident,
        &shim_doc,
        quote! { handle: u64, #(#params,)* #(#out)* },
        body,
    )
}

/// Renders both cfg variants of one shim symbol.
fn shim_pair(
    ident: &proc_macro2::Ident,
    doc: &str,
    params: TokenStream,
    body: TokenStream,
) -> TokenStream {
    let debug_shim = quote! {
        #[cfg(debug_assertions)]
        #[unsafe(no_mangle)]
        #[doc = #doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #ident(#params) -> ::bffi_core::ErrorCode {
            #body
        }
    };
    let release_shim = quote! {
        #[cfg(not(debug_assertions))]
        #[unsafe(no_mangle)]
        #[doc = #doc]
        #[allow(clippy::not_unsafe_ptr_arg_deref)]
        pub extern "C" fn #ident(#params) -> ::bffi_core::ErrorCode {
            ::bffi_core::boundary::run_extern_body(move || { #body })
        }
    };
    quote! { #debug_shim #release_shim }
}

/// The `&str` parameter conversion preamble (cstring -> UTF-8 view).
fn str_conversions(params: &[MethodParam]) -> TokenStream {
    let mut body = TokenStream::new();
    for (index, param) in params.iter().enumerate() {
        if !matches!(param.kind, ShimKind::Str) {
            continue;
        }
        let name = param_ident(&param.name, index);
        let ptr = format_ident!("{name}_ptr");
        let bytes = format_ident!("{name}_bytes");
        let view = format_ident!("{name}_view");
        body.extend(quote! {
            if #ptr.is_null() {
                let error = ::bffi_core::BffiError::new(
                    ::bffi_core::ErrorCode::NullPointer,
                    "string argument pointer is null",
                );
                ::bffi_core::set_last_error(error);
                return ::bffi_core::ErrorCode::NullPointer;
            }
            // SAFETY: bun:ffi hands out NUL-terminated cstrings for `&str`
            // parameters (DESIGN.md §6.3); the pointer is null-checked above.
            let #bytes = unsafe { ::std::ffi::CStr::from_ptr(#ptr) }.to_bytes();
            let #view = match ::bffi_types::unsafe_zero_copy::str_view(#bytes) {
                ::std::result::Result::Ok(v) => v,
                ::std::result::Result::Err(e) => {
                    ::bffi_core::set_last_error(e);
                    return ::bffi_core::ErrorCode::InvalidUtf8;
                }
            };
        });
    }
    body
}

/// The out-parameter declaration for a return kind.
fn out_param(ret: &RetKind) -> Vec<TokenStream> {
    match ret {
        RetKind::Unit => Vec::new(),
        RetKind::Prim(prim) => {
            let ty = prim_ty(*prim);
            vec![quote! { __ret: *mut #ty }]
        }
        RetKind::BigInt(big) => {
            let ty = bigint_ty(*big);
            vec![quote! { __ret: *mut #ty }]
        }
        RetKind::Buffer(_) | RetKind::Nullable(_) => vec![quote! { __ret: *mut u64 }],
        RetKind::Result(inner) => out_param(inner),
    }
}

/// Generates the return-transport tail from the call expression.
fn ret_body(ret: &RetKind, call: TokenStream) -> TokenStream {
    match ret {
        RetKind::Unit => quote! {
            #call;
            ::bffi_core::ErrorCode::Ok
        },
        RetKind::Result(inner) => {
            let ok_tail = value_tail(inner);
            quote! {
                match #call {
                    ::std::result::Result::Ok(__value) => { #ok_tail }
                    ::std::result::Result::Err(__err) => {
                        let __msg = ::std::string::ToString::to_string(&__err);
                        ::bffi_core::set_last_error(::bffi_core::BffiError::with_source(
                            ::bffi_core::ErrorCode::DomainError,
                            __msg,
                            ::std::boxed::Box::new(__err),
                        ));
                        ::bffi_core::ErrorCode::DomainError
                    }
                }
            }
        }
        other => {
            let tail = value_tail(other);
            quote! {
                let __value = #call;
                #tail
            }
        }
    }
}

/// Consumes an already-bound `__value` and yields the transport tail.
fn value_tail(ret: &RetKind) -> TokenStream {
    match ret {
        RetKind::Unit => quote! { ::bffi_core::ErrorCode::Ok },
        RetKind::Prim(_) | RetKind::BigInt(_) => quote! {
            // SAFETY: `__ret` is non-null (checked above) and valid for one
            // `T` write per the bun:ffi out-parameter contract.
            unsafe { ::std::ptr::write(__ret, __value); }
            ::bffi_core::ErrorCode::Ok
        },
        RetKind::Buffer(ty) => {
            let conv = buffer_conv(*ty);
            quote! {
                #conv
                match ::bffi_build::runtime::store_bytes(__bytes) {
                    ::std::result::Result::Ok(__handle) => {
                        // SAFETY: `__ret` is non-null (checked above) and valid
                        // for one `u64` write per the bun:ffi out-parameter contract.
                        unsafe { ::std::ptr::write(__ret, __handle.as_u64()); }
                        ::bffi_core::ErrorCode::Ok
                    }
                    ::std::result::Result::Err(__e) => {
                        ::bffi_core::set_last_error(::bffi_core::BffiError::from(__e));
                        ::bffi_core::ErrorCode::TableFull
                    }
                }
            }
        }
        RetKind::Nullable(ty) => {
            let some_tail = value_tail(&RetKind::Buffer(*ty));
            quote! {
                match __value {
                    ::std::option::Option::Some(__value) => { #some_tail }
                    ::std::option::Option::None => {
                        // SAFETY: `__ret` is non-null (checked above) and valid for
                        // one `u64` write; `0` is the documented null handle.
                        unsafe { ::std::ptr::write(__ret, 0_u64); }
                        ::bffi_core::ErrorCode::Ok
                    }
                }
            }
        }
        // Unreachable: `ret_body` unwraps `Result` first.
        RetKind::Result(_) => quote! { ::bffi_core::ErrorCode::Ok },
    }
}

/// Converts a bound `__value` into `__bytes: CopiedBuf`.
fn buffer_conv(ty: BufferTy) -> TokenStream {
    match ty {
        BufferTy::String => quote! {
            let __bytes = ::bffi_types::CopiedBuf::from_vec(__value.into_bytes());
        },
        BufferTy::ByteVec => quote! {
            let __bytes = ::bffi_types::CopiedBuf::from_vec(__value);
        },
        BufferTy::CopiedBuf => quote! {
            let __bytes = __value;
        },
    }
}

/// Declares one shim parameter.
fn shim_param(param: &MethodParam, index: usize) -> TokenStream {
    let name = param_ident(&param.name, index);
    match param.kind {
        ShimKind::Str => {
            let ptr = format_ident!("{name}_ptr");
            quote! { #ptr: *const ::std::os::raw::c_char }
        }
        ShimKind::Prim(prim) => {
            let ty = prim_ty(prim);
            quote! { #name: #ty }
        }
        ShimKind::BigInt(big) => {
            let ty = bigint_ty(big);
            quote! { #name: #ty }
        }
    }
}

/// Sanitizes a parameter name into a usable shim identifier
/// (positional fallback for `_`/keywords, same contract as bffi-macros).
fn param_ident(name: &str, index: usize) -> proc_macro2::Ident {
    syn::parse_str::<proc_macro2::Ident>(name).unwrap_or_else(|_| format_ident!("__arg{index}"))
}

/// The Rust type of a small boundary primitive.
fn prim_ty(prim: PrimTy) -> TokenStream {
    match prim {
        PrimTy::I8 => quote! { i8 },
        PrimTy::I16 => quote! { i16 },
        PrimTy::I32 => quote! { i32 },
        PrimTy::U8 => quote! { u8 },
        PrimTy::U16 => quote! { u16 },
        PrimTy::U32 => quote! { u32 },
        PrimTy::F32 => quote! { f32 },
        PrimTy::F64 => quote! { f64 },
        PrimTy::Bool => quote! { bool },
    }
}

/// The Rust type of a 64-bit boundary integer.
fn bigint_ty(big: BigIntTy) -> TokenStream {
    match big {
        BigIntTy::I64 => quote! { i64 },
        BigIntTy::U64 => quote! { u64 },
    }
}
