//! Integration tests: the exports generated by
//! `bffi_runtime_abi!()` are called directly from Rust (the P1 shim
//! testing model - no Bun in the loop). The macro expands here, into
//! this test binary, exactly like it would expand into a user cdylib.
//!
//! Numeric codes below follow the C ABI contract: `0` = `ErrorCode::Ok`,
//! `4` = `ErrorCode::InvalidHandle`, `2` = `ErrorCode::Panic`.
#![allow(missing_docs)]
#![allow(clippy::expect_used, clippy::unwrap_used)]

bffi_build::bffi_runtime_abi!();

use bffi_core::{BffiError, ErrorCode, Handle};
use bffi_error::JsErrorName;
use bffi_types::CopiedBuf;

fn store(bytes: &[u8]) -> u64 {
    bffi_build::runtime::store_bytes(CopiedBuf::from_slice(bytes))
        .expect("buffer table must have room")
        .as_u64()
}

#[test]
fn buffer_pair_reads_stored_bytes_and_free_releases() {
    let handle = store(b"payload");

    let ptr = bffi_buffer(handle);
    assert!(!ptr.is_null(), "a live handle must expose a pointer");
    assert_eq!(bffi_buffer_length(handle), 7);
    // SAFETY: the export handed out the pointer to exactly
    // `bffi_buffer_length(handle)` owned bytes; the handle is live.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, bffi_buffer_length(handle) as usize) };
    assert_eq!(bytes, b"payload");

    assert_eq!(bffi_types_free(handle), ErrorCode::Ok.as_u32());
    assert_eq!(bffi_types_free(handle), ErrorCode::InvalidHandle.as_u32());
    assert!(bffi_buffer(handle).is_null(), "stale handle -> null");
    assert_eq!(bffi_buffer_length(handle), 0);
}

#[test]
fn buffer_exports_reject_null_and_foreign_handles() {
    assert!(bffi_buffer(0).is_null(), "null handle -> null pointer");
    assert_eq!(bffi_buffer_length(0), 0);
    assert_eq!(bffi_types_free(0), ErrorCode::InvalidHandle.as_u32());

    let handle = store(b"x");
    // Same generation/index but a foreign tag: the tag barrier must
    // reject it.
    let live = Handle::from_raw(handle);
    let foreign = Handle::new(FOREIGN_TAG, live.generation(), live.index());
    assert!(bffi_buffer(foreign.as_u64()).is_null());
    assert_eq!(bffi_buffer_length(foreign.as_u64()), 0);
    assert_eq!(
        bffi_types_free(foreign.as_u64()),
        ErrorCode::InvalidHandle.as_u32()
    );
    assert_eq!(bffi_types_free(handle), ErrorCode::Ok.as_u32());
}

// Test-only tag outside every crate-owned range (bffi-build owns
// 0x0400-0x0401, user range starts at 0x8000).
const FOREIGN_TAG: bffi_core::TypeTag = bffi_core::TypeTag(0x8000);

#[test]
fn error_exports_expose_name_message_and_free() {
    assert_eq!(
        bffi_error_take_last(),
        0,
        "test threads must start with a clean slot"
    );

    bffi_core::set_last_error(BffiError::new(
        ErrorCode::InvalidUtf8,
        "byte 0xFF at position 2",
    ));
    let handle = bffi_error_take_last();
    assert_ne!(handle, 0, "a stored error must produce a handle");

    assert_eq!(bffi_error_name(handle), 2, "InvalidUtf8 -> TypeError");
    assert_eq!(bffi_error_message_len(handle), 23);
    // SAFETY: the export handed out the pointer to exactly
    // `bffi_error_message_len(handle)` owned UTF-8 bytes; the handle is
    // live until bffi_error_free.
    let message = unsafe {
        std::slice::from_raw_parts(
            bffi_error_message_ptr(handle),
            bffi_error_message_len(handle) as usize,
        )
    };
    assert_eq!(message, b"byte 0xFF at position 2");

    assert_eq!(bffi_error_free(handle), ErrorCode::Ok.as_u32());
    assert_eq!(bffi_error_free(handle), ErrorCode::InvalidHandle.as_u32());
    assert_eq!(bffi_error_name(handle), 0, "stale handle -> invalid");
    assert!(bffi_error_message_ptr(handle).is_null());
    assert_eq!(bffi_error_message_len(handle), 0);

    // The slot was drained: a second take sees nothing.
    assert_eq!(bffi_error_take_last(), 0);
}

#[test]
fn error_exports_map_every_js_name_and_reject_invalid_handles() {
    for (code, expected) in [
        (ErrorCode::Error, 1_u32),
        (ErrorCode::InvalidUtf8, 2),
        (ErrorCode::NumberOutOfRange, 3),
    ] {
        bffi_core::set_last_error(BffiError::new(code, "detail"));
        let handle = bffi_error_take_last();
        assert_ne!(handle, 0);
        assert_eq!(bffi_error_name(handle), expected, "for {code:?}");
        assert_eq!(bffi_error_free(handle), ErrorCode::Ok.as_u32());
    }

    assert_eq!(bffi_error_name(0), 0);
    assert!(bffi_error_message_ptr(0).is_null());
    assert_eq!(bffi_error_message_len(0), 0);
    assert_eq!(bffi_error_free(0), ErrorCode::InvalidHandle.as_u32());
}

#[test]
fn drained_error_names_stay_in_sync_with_bffi_error() {
    // The u32 mapping is the JS-facing twin of JsErrorName.
    assert_eq!(JsErrorName::Error.as_str(), "Error");
    assert_eq!(JsErrorName::TypeError.as_str(), "TypeError");
    assert_eq!(JsErrorName::RangeError.as_str(), "RangeError");
}

#[test]
fn concurrent_store_and_free_through_exports() {
    std::thread::scope(|scope| {
        for worker in 0..4_u64 {
            scope.spawn(move || {
                for step in 0..64_u64 {
                    let handle = store(&[worker as u8, step as u8]);
                    assert!(!bffi_buffer(handle).is_null());
                    assert_eq!(bffi_buffer_length(handle), 2);
                    assert_eq!(bffi_types_free(handle), ErrorCode::Ok.as_u32());
                }
            });
        }
    });
}
