// @generated by bffi codegen - do not edit.
// Source module: native

import { createApi, type ApiOf, type ModuleJson } from "@z2net/bffi";

const moduleJson = {
  "bffi": 1,
  "module": "native",
  "functions": [
    {
      "name": "add",
      "export": "bffi_add",
      "docs": [
        "Adds two numbers."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "shout",
      "export": "bffi_shout",
      "docs": [
        "Returns an uppercased greeting (string return through the",
        "transient-buffer pair)."
      ],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "version",
      "export": "bffi_version",
      "docs": [
        "The version of this library (static string return)."
      ],
      "params": [],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    }
  ],
  "classes": []
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
