// @generated by bffi-dts - do not edit.
// Source module: shapes

/** A native counter. */
export class counter {
  /** Creates a counter. */
  constructor(start: number);
  /** The current value. */
  get value(): number;
  /** Adds one and returns the new value. */
  increment(): number;
  _class(): void;
}
