// @generated by bffi-dts - do not edit.
// Source module: kitchen

/** Adds two numbers. */
export function add(a: number, b: number): number;

/**
 * Stores a value.
 * Returns nothing.
 */
export function _class(_delete: bigint, data: Uint8Array, flag: boolean): void;

/** Greets. */
export function greet(name: string): string;

export function noop(): void;
