// @generated by bffi-dts - do not edit.
// Source module: api

/** Adds two numbers. */
export function add(a: number, b: number): number;

/** Remembers the length of the greeting. */
export function greet(name: string): void;

/** Returns the length of the last greeting. */
export function greet_len(): number;

/** Returns an uppercased greeting as a buffer handle. */
export function shout(name: string): string;

/**
 * Copies the borrowed bytes into a fresh buffer and returns its
 * handle: the borrowed `&[u8]` parameter travels as a `(ptr, len)`
 * pair (CALLING-CONVENTION.md §3) and stays valid only for the
 * duration of the call, so the documented copy-on-return policy
 * applies.
 */
export function echo_buffer(data: Uint8Array): Uint8Array;

/** Divides, reporting a domain error through the err channel. */
export function checked_div(a: number, b: number): number;

/**
 * Always panics: the release build must convert this into
 * `ErrorCode::Panic` plus a last error, not abort Bun.
 */
export function boom(): number;

/**
 * Verification export (P1 type matrix): mirrors an `i64` through the
 * bigint parameter and out-parameter paths.
 */
export function mirror_i64(x: bigint): bigint;

/**
 * Verification export (P1 type matrix): mirrors a `u64` across the
 * full unsigned range, including values beyond
 * `Number.MAX_SAFE_INTEGER`.
 */
export function mirror_u64(x: bigint): bigint;

/**
 * Verification export (P1 type matrix): reports the parity of a
 * `u64` through the bool parameter and return paths.
 */
export function is_even(x: bigint): boolean;

/**
 * Facade-only mode probe: `crate = "bffi"` makes the generated shim
 * and descriptor resolve through the `bffi` facade namespaces
 * (`::bffi::core`, `::bffi::dts`, ...) instead of the direct
 * dependencies. The other functions above stay in default mode, so
 * both modes compile side by side in one crate.
 */
export function facade_probe(x: number): number;

/**
 * The `#[bffi_async]` macro: the spawn shim and `Promise<u32>`
 * descriptor are generated; `js/async.test.ts` awaits the value.
 */
export function example_compute(x: number): Promise<number>;

/**
 * A native class: exercised end-to-end through bun:ffi.
 * A native counter.
 */
export class counter {
  /** Creates a counter. */
  constructor(start: number);
  get value(): number;
  /** Adds one and returns the new value. */
  increment(): number;
}
