// @generated by bffi-dts - do not edit.
// Source module: api

/** Adds two numbers. */
export function add(a: number, b: number): number;

/** Remembers the length of the greeting. */
export function greet(name: string): void;

/** Returns the length of the last greeting. */
export function greet_len(): number;

/** Returns an uppercased greeting as a buffer handle. */
export function shout(name: string): string;

/** Divides, reporting a domain error through the err channel. */
export function checked_div(a: number, b: number): number;

/**
 * Always panics: the release build must convert this into
 * `ErrorCode::Panic` plus a last error, not abort Bun.
 */
export function boom(): number;

/**
 * Verification export (P1 type matrix): mirrors an `i64` through the
 * bigint parameter and out-parameter paths.
 */
export function mirror_i64(x: bigint): bigint;

/**
 * Verification export (P1 type matrix): mirrors a `u64` across the
 * full unsigned range, including values beyond
 * `Number.MAX_SAFE_INTEGER`.
 */
export function mirror_u64(x: bigint): bigint;

/**
 * Verification export (P1 type matrix): reports the parity of a
 * `u64` through the bool parameter and return paths.
 */
export function is_even(x: bigint): boolean;
