// @generated by bffi codegen - do not edit.
// Source module: api

import { createApi, type ApiOf, type ModuleJson } from "../../../packages/bffi-loader/src/index.ts";

const moduleJson = {
  "bffi": 1,
  "module": "api",
  "functions": [
    {
      "name": "add",
      "export": "bffi_add",
      "docs": [
        "Adds two numbers."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "greet",
      "export": "bffi_greet",
      "docs": [
        "Remembers the length of the greeting."
      ],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "void",
        "abi": "void"
      }
    },
    {
      "name": "greet_len",
      "export": "bffi_greet_len",
      "docs": [
        "Returns the length of the last greeting."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "shout",
      "export": "bffi_shout",
      "docs": [
        "Returns an uppercased greeting as a buffer handle."
      ],
      "params": [
        {
          "name": "name",
          "ts": "string",
          "abi": "cstring"
        }
      ],
      "ret": {
        "ts": "string",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "echo_buffer",
      "export": "bffi_echo_buffer",
      "docs": [
        "Copies the borrowed bytes into a fresh buffer and returns its",
        "handle: the borrowed `&[u8]` parameter travels as a `(ptr, len)`",
        "pair (CALLING-CONVENTION.md §3) and stays valid only for the",
        "duration of the call, so the documented copy-on-return policy",
        "applies."
      ],
      "params": [
        {
          "name": "data",
          "ts": "Uint8Array",
          "abi": "ptr_len"
        }
      ],
      "ret": {
        "ts": "Uint8Array",
        "abi": "buffer"
      },
      "out": "handle"
    },
    {
      "name": "checked_div",
      "export": "bffi_checked_div",
      "docs": [
        "Divides, reporting a domain error through the err channel."
      ],
      "params": [
        {
          "name": "a",
          "ts": "number",
          "abi": "u32"
        },
        {
          "name": "b",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "boom",
      "export": "bffi_boom",
      "docs": [
        "Always panics: the release build must convert this into",
        "`ErrorCode::Panic` plus a last error, not abort Bun."
      ],
      "params": [],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "mirror_i64",
      "export": "bffi_mirror_i64",
      "docs": [
        "Verification export (P1 type matrix): mirrors an `i64` through the",
        "bigint parameter and out-parameter paths."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "i64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "i64"
      },
      "out": "i64"
    },
    {
      "name": "mirror_u64",
      "export": "bffi_mirror_u64",
      "docs": [
        "Verification export (P1 type matrix): mirrors a `u64` across the",
        "full unsigned range, including values beyond",
        "`Number.MAX_SAFE_INTEGER`."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "bigint",
        "abi": "u64"
      },
      "out": "u64"
    },
    {
      "name": "is_even",
      "export": "bffi_is_even",
      "docs": [
        "Verification export (P1 type matrix): reports the parity of a",
        "`u64` through the bool parameter and return paths."
      ],
      "params": [
        {
          "name": "x",
          "ts": "bigint",
          "abi": "u64"
        }
      ],
      "ret": {
        "ts": "boolean",
        "abi": "bool"
      },
      "out": "bool"
    },
    {
      "name": "facade_probe",
      "export": "bffi_facade_probe",
      "docs": [
        "Facade-only mode probe: `crate = \"bffi\"` makes the generated shim",
        "and descriptor resolve through the `bffi` facade namespaces",
        "(`::bffi::core`, `::bffi::dts`, ...) instead of the direct",
        "dependencies. The other functions above stay in default mode, so",
        "both modes compile side by side in one crate."
      ],
      "params": [
        {
          "name": "x",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "number",
        "abi": "u32"
      },
      "out": "u32"
    },
    {
      "name": "example_compute",
      "export": "bffi_example_compute",
      "docs": [
        "The `#[bffi_async]` macro: the spawn shim and `Promise<u32>`",
        "descriptor are generated; `js/async.test.ts` awaits the value."
      ],
      "params": [
        {
          "name": "x",
          "ts": "number",
          "abi": "u32"
        }
      ],
      "ret": {
        "ts": "Promise<number>",
        "abi": "task"
      },
      "out": "handle"
    }
  ],
  "classes": [
    {
      "name": "counter",
      "release": "bffi_counter_release",
      "docs": [
        "A native class: exercised end-to-end through bun:ffi.",
        "A native counter."
      ],
      "constructor": {
        "name": "constructor",
        "export": "bffi_counter_new",
        "docs": [
          "Creates a counter."
        ],
        "params": [
          {
            "name": "start",
            "ts": "number",
            "abi": "u32"
          }
        ],
        "ret": {
          "ts": "bigint",
          "abi": "handle"
        },
        "out": "handle"
      },
      "fields": [
        {
          "name": "value",
          "export": "bffi_counter_value_get",
          "docs": [],
          "ts": "number",
          "out": "u32"
        }
      ],
      "methods": [
        {
          "name": "increment",
          "export": "bffi_counter_increment",
          "docs": [
            "Adds one and returns the new value."
          ],
          "params": [],
          "ret": {
            "ts": "number",
            "abi": "u32"
          },
          "out": "u32"
        }
      ]
    }
  ]
} as const satisfies ModuleJson;

/** Opens the native library at `libraryPath` and returns the typed API. */
export function createApiFromJson(libraryPath: string): ApiOf<typeof moduleJson> {
  return createApi(moduleJson, libraryPath);
}

export type Api = ReturnType<typeof createApiFromJson>;

export { moduleJson };
