//! The declarative generator of the JS-facing C ABI exports.
//!
//! [`bffi_runtime_abi!`](crate::bffi_runtime_abi) expands - in the USER
//! crate, not here - into the eight `extern "C"` symbols JavaScript
//! calls through `bun:ffi`. Expansion must happen in the user crate
//! because the linker may drop unused `#[no_mangle]` symbols that live
//! in an rlib dependency; symbols defined by the final cdylib itself
//! always survive. This mirrors the `#[bffi]` shim model (P1): the
//! generator lives in the framework crate, the generated code in the
//! user crate (HANDOFF §3.6 - the ABI layer belongs to `bffi-build`).
//!
//! Every generated export follows the `bffi_extern!` build policy
//! (DESIGN §6.5):
//!
//! - **debug** builds run the body bare (a panic aborts, easier
//!   debugging);
//! - **release** builds wrap the body in
//!   [`run_extern_body_or`](bffi_core::run_extern_body_or): the panic
//!   is stored as the last error and the export's documented "nothing"
//!   sentinel is returned (`0`, null, or the
//!   [`ErrorCode::Panic`](bffi_core::ErrorCode) numeric value for the
//!   free exports).
//!
//! The module's public helpers (`*_as_u32` / `*_as_code`) exist because
//! macro-expanded code in the user crate can only name `pub` items of
//! this crate; they keep the mapping logic testable on the Rust side.

/// Maps a drained-error handle to the exported name code:
/// `1` = Error, `2` = TypeError, `3` = RangeError, `0` = invalid
/// (null/stale/foreign handle). Future `JsErrorName` variants fall
/// back to `1` (generic Error).
#[must_use]
pub fn error_name_as_u32(handle: u64) -> u32 {
    use bffi_error::JsErrorName;
    match crate::runtime::error_name(bffi_core::Handle::from_raw(handle)) {
        Some(JsErrorName::TypeError) => 2,
        Some(JsErrorName::RangeError) => 3,
        Some(JsErrorName::Error | _) => 1,
        None => 0,
    }
}

/// Releases the drained-error slot behind `handle` and returns the
/// [`bffi_core::ErrorCode`] numeric value (`0` = Ok, `4` =
/// InvalidHandle).
#[must_use]
pub fn free_error_as_code(handle: u64) -> u32 {
    if crate::runtime::free_error(bffi_core::Handle::from_raw(handle)) {
        bffi_core::ErrorCode::Ok.as_u32()
    } else {
        bffi_core::ErrorCode::InvalidHandle.as_u32()
    }
}

/// Releases the buffer slot behind `handle` and returns the
/// [`bffi_core::ErrorCode`] numeric value (`0` = Ok, `4` =
/// InvalidHandle).
#[must_use]
pub fn free_buffer_as_code(handle: u64) -> u32 {
    if crate::runtime::free_buffer(bffi_core::Handle::from_raw(handle)) {
        bffi_core::ErrorCode::Ok.as_u32()
    } else {
        bffi_core::ErrorCode::InvalidHandle.as_u32()
    }
}

/// Generates the eight JS-facing runtime exports.
///
/// Call once, at the root of the cdylib crate:
///
/// ```text
/// bffi_build::bffi_runtime_abi!();
/// ```
///
/// The user crate must depend on `bffi-core` and `bffi-build` (the
/// generated code uses `::bffi_core` and `$crate` = `::bffi_build`
/// paths only).
///
/// # Generated exports
///
/// | Symbol | Signature | Sentinel on panic |
/// |---|---|---|
/// | `bffi_error_take_last` | `() -> u64` | `0` (detail stays in the TLS slot) |
/// | `bffi_error_name` | `(h: u64) -> u32` | `0` (reads as "invalid") |
/// | `bffi_error_message_ptr` | `(h: u64) -> *const u8` | null |
/// | `bffi_error_message_len` | `(h: u64) -> u64` | `0` |
/// | `bffi_error_free` | `(h: u64) -> u32` | `ErrorCode::Panic` value |
/// | `bffi_buffer` | `(h: u64) -> *const u8` | null |
/// | `bffi_buffer_length` | `(h: u64) -> u64` | `0` |
/// | `bffi_types_free` | `(h: u64) -> u32` | `ErrorCode::Panic` value |
///
/// Numeric `0` sentinels overlap with legitimate values ("no error",
/// "invalid handle", "empty message"); each export's doc comment spells
/// out the meaning. Free exports return the [`bffi_core::ErrorCode`]
/// numeric value: `0` = Ok, `4` = InvalidHandle.
#[macro_export]
macro_rules! bffi_runtime_abi {
    () => {
        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// drains the thread-local last error into a readable slot.
        /// Returns the handle as a raw `u64`, `0` when no error is
        /// stored.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_error_take_last() -> u64 {
            #[cfg(debug_assertions)]
            {
                $crate::runtime::take_error().as_u64()
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::runtime::take_error().as_u64(),
                    0_u64,
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// returns the JS constructor name of the drained error
        /// (`1` = Error, `2` = TypeError, `3` = RangeError), `0` for
        /// null/stale/foreign handles.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_error_name(handle: u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::abi::error_name_as_u32(handle)
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::abi::error_name_as_u32(handle),
                    0_u32,
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// returns the pointer to the drained error's UTF-8 message
        /// bytes (valid until `bffi_error_free`), null for invalid
        /// handles.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_error_message_ptr(handle: u64) -> *const u8 {
            #[cfg(debug_assertions)]
            {
                $crate::runtime::error_message_ptr(::bffi_core::Handle::from_raw(handle))
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::runtime::error_message_ptr(::bffi_core::Handle::from_raw(handle)),
                    ::std::ptr::null(),
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// returns the byte length of the drained error's message,
        /// `0` for invalid handles.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_error_message_len(handle: u64) -> u64 {
            #[cfg(debug_assertions)]
            {
                $crate::runtime::error_message_len(::bffi_core::Handle::from_raw(handle))
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::runtime::error_message_len(::bffi_core::Handle::from_raw(handle)),
                    0_u64,
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// releases the drained-error slot. Returns the
        /// [`ErrorCode`](bffi_core::ErrorCode) numeric value
        /// (`0` = Ok, `4` = InvalidHandle).
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_error_free(handle: u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::abi::free_error_as_code(handle)
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::abi::free_error_as_code(handle),
                    ::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// returns the pointer to the bytes behind the buffer handle
        /// (valid until `bffi_types_free`), null for invalid handles.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_buffer(handle: u64) -> *const u8 {
            #[cfg(debug_assertions)]
            {
                $crate::runtime::buffer_ptr(::bffi_core::Handle::from_raw(handle))
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::runtime::buffer_ptr(::bffi_core::Handle::from_raw(handle)),
                    ::std::ptr::null(),
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// returns the byte length behind the buffer handle, `0` for
        /// invalid handles.
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_buffer_length(handle: u64) -> u64 {
            #[cfg(debug_assertions)]
            {
                $crate::runtime::buffer_len(::bffi_core::Handle::from_raw(handle))
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::runtime::buffer_len(::bffi_core::Handle::from_raw(handle)),
                    0_u64,
                )
            }
        }

        /// C ABI export generated by `bffi_build::bffi_runtime_abi!()`:
        /// releases the buffer slot. Returns the
        /// [`ErrorCode`](bffi_core::ErrorCode) numeric value
        /// (`0` = Ok, `4` = InvalidHandle).
        #[unsafe(no_mangle)]
        pub extern "C" fn bffi_types_free(handle: u64) -> u32 {
            #[cfg(debug_assertions)]
            {
                $crate::abi::free_buffer_as_code(handle)
            }
            #[cfg(not(debug_assertions))]
            {
                ::bffi_core::boundary::run_extern_body_or(
                    || $crate::abi::free_buffer_as_code(handle),
                    ::bffi_core::ErrorCode::Panic.as_u32(),
                )
            }
        }
    };
}
